version: '2'
services:
  nginx:
    build:
      context: ./docker/images/nginx
      args:
        - USER_ID
        - GROUP_ID
    container_name: library_nginx
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - ./:/var/www
    links:
      - php
    depends_on:
      - php
      - sqlite
      - sqlite_test
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=api.library.loc
    networks:
      - default
  php:
    build:
      context: ./docker/images/php
      args:
        - USER_ID
        - GROUP_ID
    container_name: library_yii2_php
    links:
      - sqlite
      - sqlite_test
    volumes:
      - ./:/var/www
      - ./docker/logs/:/var/log/php-fpm
    environment:
        XDEBUG_CONFIG: "remote_enable=1 remote_autostart=1 remote_port=9000 remote_connect_back=1"
        TZ: Europe/Moscow
  sqlite:
    image: nouchka/sqlite3:latest
    container_name: library_sqlite
    ports:
      - "11701:3306"
    volumes:
      - ./docker/data/sqlite:/var/lib/sqlite
      - ./docker/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpwd
      MYSQL_DATABASE: db
      TZ: Europe/Moscow
  sqlite_test:
    image: nouchka/sqlite3:latest
    container_name: library_sqlite_test
    ports:
      - "11702:3306"
    volumes:
      - ./docker/data/sqlite_test:/var/lib/sqlite
      - ./docker/dumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpassw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpwd
      MYSQL_DATABASE: db
      TZ: Europe/Moscow
networks:
  default:
    driver: bridge
